version: "3"

services:
  api:
    build: .
    image: node:17
    working_dir: /app/api-chat-message
    command: bash -c "npm install && npm run dev"
    ports: 
      - 3001:3001
    environment:
     - API_PORT=3001
    volumes:
      - ./api-chat-message:/app/api-chat-message

  # client:
  #   build: .
  #   image: node:17
  #   working_dir: /app/message-app
  #   command:  bash -c "npm install && npm run dev"
  #   ports: 
  #     - 3000:3000
  #   volumes:
  #     - ./message-app:/app/message-app